# [Choice] Node.js version
# Full list: https://mcr.microsoft.com/v2/devcontainers/typescript-node/tags/list
ARG VARIANT="latest"
FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:${VARIANT}

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment this section to install more global node packages
# RUN su node -c "npm install -g ts-node npm-check-updates"

# Set Timezone
ENV TZ Asia/Tokyo
