version: '3'
services:
  workspace:
    build:
      context: .
      dockerfile: workspace/Dockerfile
      args:
        VARIANT: 1-20-bookworm
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
  mysql:
    image: mysql:8.0.32
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
  redis:
    image: redis:latest
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    command: azurite-blob --blobHost 0.0.0.0 --skipApiVersionCheck
  elasticsearch:
    build:
      context: .
      dockerfile: elasticsearch/Dockerfile
      args:
        VARIANT: 8.12.2
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
